const PRODUCTS = [
  {
    slug: "cv-general-modern",
    category: "כללי",
    categorySlug: "general",
    title: "תבנית קורות חיים — סיידבר",
    shortDesc: "עמודת צד כהה עם אווטאר ראשי תיבות, ציר זמן לניסיון. מתאים לכל תחום.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-general-modern.webp",
    featured: true,
    heroDesc: "עיצוב דו-טורי מודרני: עמודת צד כהה עם אווטאר ראשי-תיבות, פרטי קשר וכישורים כתגיות, לצד ציר זמן לניסיון התעסוקתי. מתאים לכל תחום ולכל שלב בקריירה.",
    checklist: [
      "עורכים את הפרטים שלכם ורואים תוצאה חיה באתר",
      "בוחרים את הצבע שמתאים לכם באופן אישי",
      "הורדת PDF חינמית לגמרי — בלי תשלום",
      "עברית או אנגלית, לבחירתכם, באותו הבילדר",
    ],
  },
  {
    slug: "cv-dev-dark",
    category: "תכנות",
    categorySlug: "dev",
    title: "תבנית קורות חיים — מפתחים (סיידבר כהה)",
    shortDesc: "עמודת צד נייבי כהה, ציר זמן טכני, תגיות טכנולוגיות. מתאים למפתחים.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-dev-dark.webp",
    heroDesc: "עיצוב דו-טורי טכנולוגי עם עמודת צד נייבי כהה — טכנולוגיות מוצגות כתגיות, קישור ל-GitHub בולט, וציר זמן שמדגיש פרויקטים והשפעה מדידה.",
    checklist: [
      "טכנולוגיות מוצגות כתגיות, לא רשימה יבשה",
      "מקום ייעודי לקישור GitHub / פורטפוליו",
      "עריכה חיה באתר, כולל שינוי צבע העמודה",
      "מתאים למפתחים בכל הרמות — מג'וניור ועד סניור",
    ],
  },
  {
    slug: "cv-dev-minimal",
    category: "תכנות",
    categorySlug: "dev",
    title: "תבנית קורות חיים — מפתחים (נועז)",
    shortDesc: "שם ענק, תג תפקיד צבעוני, כותרות ממוספרות. עיצוב עכשווי ובולט.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-dev-minimal.webp",
    heroDesc: "עיצוב עורכי-דין עכשווי: שם גדול ובולט, תג תפקיד צבעוני, כותרות סעיפים ממוספרות וכישורים כתגיות. מתאים למי שרוצה להיראות עדכני בלי להתפשר על סדר.",
    checklist: [
      "טיפוגרפיה גדולה ובולטת שמושכת תשומת לב",
      "מקום לקישורי GitHub, פורטפוליו ואתר אישי",
      "עריכה חיה באתר לפני ההורדה",
      "מתאים גם למעבר בין תפקידים טכניים",
    ],
  },
  {
    slug: "cv-dev-fullstack",
    category: "תכנות",
    categorySlug: "dev",
    title: "תבנית קורות חיים — Full-Stack (סיידבר טורקיז)",
    shortDesc: "עמודת צד טורקיז עם סעיף פרויקטים. מתאים למפתחי Full-Stack.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-dev-fullstack.webp",
    heroDesc: "עיצוב דו-טורי בגוון טורקיז עם סעיף פרויקטים ייעודי — מקום להציג פרויקטים אישיים עם קישור ל-GitHub, לצד ניסיון תעסוקתי. מתאים במיוחד למפתחים שרוצים להראות גם עשייה עצמאית, לא רק מקומות עבודה.",
    checklist: [
      "סעיף פרויקטים נפרד — עם קישור לכל פרויקט",
      "עמודת צד עם תגיות טכנולוגיות",
      "עריכה חיה באתר, כולל שינוי צבע",
      "מתאים גם לבוגרי הסבה טכנולוגית",
    ],
  },
  {
    slug: "cv-dev-junior",
    category: "תכנות",
    categorySlug: "dev",
    title: "תבנית קורות חיים — ג׳וניור / בוגרי בוטקאמפ (נועז)",
    shortDesc: "מדגישה פרויקטים והשכלה כשאין עוד הרבה ניסיון תעסוקתי.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-dev-junior.webp",
    heroDesc: "עיצוב נועז שבנוי במיוחד למי שנמצא בתחילת הדרך בתכנות — בוגרי בוטקאמפ, הסבה טכנולוגית או תואר ראשון. סעיף הפרויקטים תופס מקום מרכזי, כדי לפצות על ניסיון תעסוקתי מצומצם.",
    checklist: [
      "בנויה להדגיש פרויקטים במקום ניסיון תעסוקתי",
      "מקום להציג פרויקט גמר / בוטקאמפ בבולטות",
      "עריכה חיה באתר לפני ההורדה",
      "מתאים גם למעבר קריירה לתכנות",
    ],
  },
  {
    slug: "cv-design-creative",
    category: "עיצוב",
    categorySlug: "design",
    title: "תבנית קורות חיים — מעצבים (נועז)",
    shortDesc: "שם ענק, צורה גרפית דקורטיבית, תגיות צבעוניות. לא עוד תבנית משעממת.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-design-creative.webp",
    heroDesc: "עיצוב עורכי-דין נועז עם טיפוגרפיה גדולה, צורה גרפית דקורטיבית ברקע וכישורים כתגיות צבעוניות — קורות חיים שמראים טעם עיצובי, לא רק מספרים עליו. מקום ייעודי לקישור לפורטפוליו.",
    checklist: [
      "טיפוגרפיה ענקית וצורה גרפית שמושכות את העין",
      "מקום ייעודי לקישור פורטפוליו",
      "בוחרים בעצמכם את הצבע הראשי בבילדר החי",
      "מתאים למעצבי גרפיקה, UX/UI ומיתוג",
    ],
  },
  {
    slug: "cv-design-portfolio",
    category: "עיצוב",
    categorySlug: "design",
    title: "תבנית קורות חיים — מעצבים (סיידבר)",
    shortDesc: "עמודת צד בגוון בורדו, אווטאר ראשי תיבות, ציר זמן לניסיון.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-design-portfolio.webp",
    heroDesc: "עיצוב דו-טורי מאופק עם עמודת צד בגוון בורדו עדין, אווטאר ראשי-תיבות וציר זמן לניסיון. מתאימה למעצבים שמעדיפים שהעבודות שלהם (בפורטפוליו הנפרד) ידברו במקום קורות החיים.",
    checklist: [
      "עמודת צד מסודרת עם כל הפרטים במבט אחד",
      "מקום לקישור פורטפוליו / אתר אישי",
      "עריכה חיה באתר לפני ההורדה",
      "מתאים גם למעצבי דפוס ומיתוג",
    ],
  },
  {
    slug: "cv-design-uiux",
    category: "עיצוב",
    categorySlug: "design",
    title: "תבנית קורות חיים — UI/UX (סיידבר טורקיז)",
    shortDesc: "עמודת צד טורקיז, אווטאר ראשי תיבות, מקום לקישור פורטפוליו.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-design-uiux.webp",
    heroDesc: "עיצוב דו-טורי מקצועי בגוון טורקיז, עם דגש על ניסיון במחקר משתמשים ובדיקות. מתאים למעצבי UI/UX שעובדים בתהליך מוצר מובנה.",
    checklist: [
      "עמודת צד עם כל הפרטים במבט אחד",
      "מקום ייעודי לקישור פורטפוליו (Dribbble/Behance)",
      "עריכה חיה באתר, כולל שינוי צבע",
      "מתאים למעצבי מוצר ו-UX Research",
    ],
  },
  {
    slug: "cv-design-motion",
    category: "עיצוב",
    categorySlug: "design",
    title: "תבנית קורות חיים — מושן/וידאו (נועז)",
    shortDesc: "טיפוגרפיה גדולה בסגנון קריאייטיב, לאנשי מושן ווידאו.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-design-motion.webp",
    heroDesc: "עיצוב נועז בגוון סגול, עם טיפוגרפיה גדולה וכותרות ממוספרות — מתאים למעצבי מושן, עורכי וידאו ואנשי קריאייטיב שרוצים קורות חיים שמרגישים כמו חלק מהפורטפוליו שלהם.",
    checklist: [
      "טיפוגרפיה גדולה שמושכת תשומת לב מיידית",
      "מקום לקישור לשואו-ריל או ערוץ Vimeo/YouTube",
      "בוחרים בעצמכם את הצבע הראשי בבילדר החי",
      "מתאים למעצבי מושן, עריכת וידאו ואנימציה",
    ],
  },
  {
    slug: "cv-accounting-classic",
    category: "הנהלת חשבונות",
    categorySlug: "accounting",
    title: "תבנית קורות חיים — הנהלת חשבונות (קלאסי)",
    shortDesc: "עיצוב שקט ומלוטש בגופן serif, כותרות ממוספרות. ידידותי ל-ATS.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-accounting-classic.webp",
    heroDesc: "עיצוב שקט ומלוטש בגופן serif קלאסי, עם כותרות סעיפים ממוספרות ומסגרת דקה — בלי צבעוניות מיותרת, אבל גם לא משעמם. מתאים לתפקידי הנהלת חשבונות, כספים ותפקידים שדורשים רושם רציני ואמין.",
    checklist: [
      "עיצוב שמרני שמתאים לתרבות ארגונית מסורתית",
      "מבנה ברור וידידותי למערכות סינון ממוחשבות (ATS)",
      "עריכה חיה באתר, הורדה חינמית תמיד",
      "מתאים להנהלת חשבונות, כספים וביקורת",
    ],
  },
  {
    slug: "cv-accounting-modern",
    category: "הנהלת חשבונות",
    categorySlug: "accounting",
    title: "תבנית קורות חיים — הנהלת חשבונות (סיידבר מודרני)",
    shortDesc: "עמודת צד טורקיז כהה, מראה עדכני יותר להנהלת חשבונות סוג 2.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-accounting-modern.webp",
    heroDesc: "עיצוב דו-טורי מודרני יותר מהגרסה הקלאסית — עדיין מקצועי ורציני, אבל עם עמודת צד צבעונית ואווטאר ראשי-תיבות. מתאים למי שרוצה להיראות עדכני בלי לוותר על רצינות.",
    checklist: [
      "מראה מודרני יותר מהגרסה הקלאסית, עדיין מקצועי",
      "עמודת צד עם כל הפרטים במבט אחד",
      "עריכה חיה באתר, הורדה חינמית תמיד",
      "מתאים להנהלת חשבונות סוג 1-2 בתחילת הדרך",
    ],
  },
  {
    slug: "cv-finance-analyst",
    category: "הנהלת חשבונות",
    categorySlug: "accounting",
    title: "תבנית קורות חיים — אנליסט כספים (שקט)",
    shortDesc: "עיצוב שקט ומלוטש בירוק כהה, לתפקידי ניתוח פיננסי.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-finance-analyst.webp",
    heroDesc: "עיצוב שקט ומלוטש עם כותרות ממוספרות, בגוון ירוק כהה עסקי — מתאים לאנליסטים פיננסיים, כלכלנים ותפקידי ניתוח נתונים עסקיים שדורשים רושם מדויק ומקצועי.",
    checklist: [
      "עיצוב עסקי רציני שמתאים לעולם הפיננסים",
      "מבנה ברור להצגת כלים אנליטיים (Excel, Power BI, SQL)",
      "עריכה חיה באתר, הורדה חינמית תמיד",
      "מתאים לאנליסטים, כלכלנים ותפקידי מחקר",
    ],
  },
  {
    slug: "cv-business-clean",
    category: "כללי",
    categorySlug: "general",
    title: "תבנית קורות חיים — עסקי נקי",
    shortDesc: "עיצוב שקט ומלוטש עם כותרות ממוספרות, לכל תפקיד עסקי או תפעולי.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-business-clean.webp",
    heroDesc: "עיצוב שקט ומלוטש עם אקצנט נייבי עדין וכותרות סעיפים ממוספרות — אופציה בטוחה ומקצועית לכל תפקיד שלא נכנס לקטגוריה ספציפית: תפעול, ניהול, שירות לקוחות ועוד.",
    checklist: [
      "עיצוב ניטרלי שמתאים כמעט לכל תפקיד",
      "מבנה ברור וקריא",
      "עריכה חיה באתר לפני ההורדה",
      "בחירה בטוחה כשלא בטוחים איזו תבנית להתאים",
    ],
  },
  {
    slug: "cv-sales",
    category: "כללי",
    categorySlug: "general",
    title: "תבנית קורות חיים — מכירות / פיתוח עסקי (נועז)",
    shortDesc: "טיפוגרפיה גדולה עם צורה גרפית, מדגישה יעדים והישגים במספרים.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-sales.webp",
    heroDesc: "עיצוב נועז בגוון כתום-אדום עם טיפוגרפיה גדולה — בנוי להדגיש הישגים במספרים (יעדי מכירות, הכנסות, אחוזי עמידה ביעד), בדיוק מה שגורם למגייס בתחום מכירות לעצור ולקרוא.",
    checklist: [
      "מבנה שמדגיש הישגים מדידים במספרים",
      "טיפוגרפיה גדולה שמושכת תשומת לב",
      "בוחרים בעצמכם את הצבע הראשי בבילדר החי",
      "מתאים למכירות, פיתוח עסקי ומנהלי לקוחות",
    ],
  },
  {
    slug: "cv-customer-service",
    category: "כללי",
    categorySlug: "general",
    title: "תבנית קורות חיים — שירות לקוחות / הצלחת לקוח (סיידבר)",
    shortDesc: "עמודת צד בגוון טורקיז-אפור, מתאימה לתפקידי שירות ולקוחות.",
    price: 0,
    format: "PDF מותאם אישית",
    formatBadges: ["חינם", "PDF מותאם אישית", "עברית RTL", "בילדר חי"],
    image: "cv-customer-service.webp",
    heroDesc: "עיצוב דו-טורי נעים ומקצועי בגוון טורקיז-אפור עדין — מתאים לתפקידי שירות לקוחות, הצלחת לקוחות (Customer Success) ותמיכה טכנית, עם מבנה שמדגיש שיעורי שימור ושביעות רצון.",
    checklist: [
      "מבנה שמדגיש מדדי שירות (שימור, שביעות רצון)",
      "עמודת צד עם כל הפרטים במבט אחד",
      "עריכה חיה באתר, הורדה חינמית תמיד",
      "מתאים לשירות לקוחות, הצלחת לקוח ותמיכה",
    ],
  },
  {
    slug: "biz-deck-profile",
    category: "מצגות",
    categorySlug: "deck",
    topicSlug: "business",
    title: "תבנית פרופיל חברה",
    shortDesc: "מצגת PowerPoint מלאה בת 7 שקפים בעיצוב אחיד. חינם.",
    price: 0,
    format: "PowerPoint (.pptx)",
    formatBadges: ["חינם", "קובץ PowerPoint (.pptx)", "7 שקפים", "16:9 · עברית RTL"],
    image: "biz-deck.webp",
    downloadUrl: "downloads/company-profile.pptx",
    heroDesc: "מצגת PowerPoint מלאה בת 7 שקפים בעיצוב אחיד ומקצועי — מושלמת לפגישות לקוחות, גיוס משקיעים או הצגת העסק שלכם. כוללת שקף פתיחה, אודותינו, שירותים, תהליך עבודה, נתונים ומספרים, צוות ויצירת קשר.",
    checklist: [
      "קובץ PowerPoint מלא לעריכה — טקסט, צבעים ותמונות",
      "פלטת צבעים אחידה שמשדרת מקצועיות",
      "שקפי נתונים ותהליך עבודה מוכנים מראש",
      "הורדה מיידית וחינמית, בהתחברות פשוטה",
    ],
  },
  {
    slug: "deck-product-launch",
    category: "מצגות",
    categorySlug: "deck",
    topicSlug: "marketing",
    title: "תבנית הצגת מוצר",
    shortDesc: "מצגת PowerPoint להשקת מוצר — בעיה, תכונות, תמחור. חינם.",
    price: 0,
    format: "PowerPoint (.pptx)",
    formatBadges: ["חינם", "קובץ PowerPoint (.pptx)", "6 שקפים", "16:9 · עברית RTL"],
    image: "deck-product-launch.webp",
    downloadUrl: "downloads/product-launch.pptx",
    featured: true,
    heroDesc: "מצגת PowerPoint להצגת מוצר או שירות חדש — כוללת שקף הבעיה שהמוצר פותר, תכונות מרכזיות, תמחור בשלוש רמות וקריאה לפעולה. מושלמת להשקות, פגישות מכירה או עמוד נחיתה מוצג.",
    checklist: [
      "מבנה שמוביל את הצופה מהבעיה אל הפתרון",
      "שקף תמחור מוכן בשלוש רמות — קל להתאמה",
      "קובץ PowerPoint מלא לעריכה",
      "הורדה מיידית וחינמית",
    ],
  },
  {
    slug: "deck-content-webinar",
    category: "מצגות",
    categorySlug: "deck",
    topicSlug: "marketing",
    title: "תבנית תוכן / וובינר",
    shortDesc: "מצגת PowerPoint להרצאה, וובינר או שיעור. חינם.",
    price: 0,
    format: "PowerPoint (.pptx)",
    formatBadges: ["חינם", "קובץ PowerPoint (.pptx)", "6 שקפים", "16:9 · עברית RTL"],
    image: "deck-content-webinar.webp",
    downloadUrl: "downloads/content-webinar.pptx",
    heroDesc: "מצגת PowerPoint להעברת תוכן — הרצאה, וובינר או שיעור. כוללת שקף אג'נדה, שקפי תוכן עם אייקונים, נקודות מפתח לסיכום ושקף סיום. מבנה ברור שקל למלא בתוכן שלכם.",
    checklist: [
      "שקף אג'נדה שמסביר לצופים למה לצפות",
      "שקפי תוכן מודגשים עם אייקון לכל נקודה",
      "שקף סיכום נקודות מפתח בסוף",
      "הורדה מיידית וחינמית",
    ],
  },
  {
    slug: "deck-investor-pitch",
    category: "מצגות",
    categorySlug: "deck",
    topicSlug: "business",
    title: "תבנית פיץ' למשקיעים",
    shortDesc: "מצגת PowerPoint לגיוס — בעיה, שוק, טרקשן, בקשה. חינם.",
    price: 0,
    format: "PowerPoint (.pptx)",
    formatBadges: ["חינם", "קובץ PowerPoint (.pptx)", "6 שקפים", "16:9 · עברית RTL"],
    image: "deck-investor-pitch.webp",
    downloadUrl: "downloads/investor-pitch.pptx",
    heroDesc: "מצגת PowerPoint למצגת משקיעים — בעיה ופתרון, גודל שוק, נתוני התקדמות (traction) ובקשת גיוס. מבנה קלאסי לפיץ' דק שמכסה את כל מה שמשקיע רוצה לראות.",
    checklist: [
      "מבנה בעיה-פתרון-שוק-טרקשן-בקשה קלאסי",
      "שקף גודל שוק (TAM/SAM/SOM) מוכן מראש",
      "שקף נתוני התקדמות עם מקום למספרים שלכם",
      "הורדה מיידית וחינמית",
    ],
  },
  {
    slug: "deck-creative-portfolio",
    category: "מצגות",
    categorySlug: "deck",
    topicSlug: "creative",
    title: "תבנית פורטפוליו יצירתי",
    shortDesc: "מצגת PowerPoint להצגת עבודות ופרויקטים. חינם.",
    price: 0,
    format: "PowerPoint (.pptx)",
    formatBadges: ["חינם", "קובץ PowerPoint (.pptx)", "5 שקפים", "16:9 · עברית RTL"],
    image: "deck-creative-portfolio.webp",
    downloadUrl: "downloads/creative-portfolio.pptx",
    heroDesc: "מצגת PowerPoint מינימליסטית ואלגנטית להצגת פורטפוליו — לפרילנסרים, מעצבים ואנשי קריאייטיב. כוללת שקף אודות, עבודות נבחרות, המלצת לקוח ויצירת קשר.",
    checklist: [
      "עיצוב מינימליסטי שנותן מקום לעבודות שלכם",
      "שקף המלצה מוכן להצגת ציטוט לקוח",
      "קובץ PowerPoint מלא לעריכה",
      "הורדה מיידית וחינמית",
    ],
  },
  {
    slug: "deck-cinematic-pitch",
    category: "מצגות",
    categorySlug: "deck",
    topicSlug: "business",
    title: "תבנית פיץ' קולנועית כהה",
    shortDesc: "מצגת PowerPoint במוד כהה עם זוהר ניאון וגרף צמיחה דרמטי. חינם.",
    price: 0,
    format: "PowerPoint (.pptx)",
    formatBadges: ["חינם", "קובץ PowerPoint (.pptx)", "6 שקפים", "16:9 · עברית RTL"],
    image: "deck-cinematic.webp",
    downloadUrl: "downloads/cinematic-dark-pitch.pptx",
    heroDesc: "מצגת PowerPoint ברקע שחור פחם עמוק עם זוהר טורקיז וסגול קוונטום — בנויה להרשים משקיעים ולקוחות. כוללת שקף פתיחה, חזון, שירותים, גרף צמיחה מעוצב, יתרונות ויצירת קשר.",
    checklist: [
      "רקע כהה עם אפקטי זוהר (glow) מאחורי הנתונים",
      "שקף נתונים עם גרף עמודות מעוצב ומודגש",
      "קובץ PowerPoint מלא לעריכה — טקסט, צבעים ותמונות",
      "הורדה מיידית וחינמית, בהתחברות פשוטה",
    ],
  },
  {
    slug: "deck-editorial-brand",
    category: "מצגות",
    categorySlug: "deck",
    topicSlug: "creative",
    title: "תבנית מגזין אופנתי",
    shortDesc: "מצגת PowerPoint בסגנון מגזין יוקרתי עם טיפוגרפיית סריף גדולה. חינם.",
    price: 0,
    format: "PowerPoint (.pptx)",
    formatBadges: ["חינם", "קובץ PowerPoint (.pptx)", "6 שקפים", "16:9 · עברית RTL"],
    image: "deck-editorial.webp",
    downloadUrl: "downloads/editorial-magazine-deck.pptx",
    heroDesc: "מצגת PowerPoint נקייה ויוקרתית שמרגישה כמו דפדוף במגזין אופנה — טיפוגרפיית סריף גדולה, חללים לבנים נדיבים וגווני אדמה עדינים. מתאימה למותגי אופנה, אדריכלים ועסקי פרימיום.",
    checklist: [
      "טיפוגרפיה אלגנטית עם פונט סריף לכותרות",
      "חללים לבנים גדולים שנותנים לתוכן לנשום",
      "קובץ PowerPoint מלא לעריכה",
      "הורדה מיידית וחינמית",
    ],
  },
  {
    slug: "deck-neopop-business",
    category: "מצגות",
    categorySlug: "deck",
    topicSlug: "marketing",
    title: "תבנית פופ-ארט אנרגטית",
    shortDesc: "מצגת PowerPoint צבעונית ונועזת בסגנון נאו-ברוטליזם. חינם.",
    price: 0,
    format: "PowerPoint (.pptx)",
    formatBadges: ["חינם", "קובץ PowerPoint (.pptx)", "6 שקפים", "16:9 · עברית RTL"],
    image: "deck-neopop.webp",
    downloadUrl: "downloads/neo-pop-business.pptx",
    heroDesc: "מצגת PowerPoint נועזת וצבעונית — צהוב חומצי, כתום מנדרינה וכחול רויאל עם מסגרות שחורות עבות בסגנון קומיקס. מושלמת להרצאות, סדנאות ומותגים צעירים שרוצים להרים את האנרגיה בחדר.",
    checklist: [
      "צבעים נועזים ומסגרות שחורות עבות בכל שקף",
      "שקפי 'מדבקות' לנתונים ולהישגים",
      "קובץ PowerPoint מלא לעריכה",
      "הורדה מיידית וחינמית",
    ],
  },
  {
    slug: "xlsx-budget",
    category: "גיליונות",
    categorySlug: "xlsx",
    topicSlug: "finance",
    title: "תבנית תקציב חודשי",
    shortDesc: "גיליון Excel למעקב הכנסות והוצאות עם סיכום אוטומטי. חינם.",
    price: 0,
    format: "Excel (.xlsx)",
    formatBadges: ["חינם", "קובץ Excel (.xlsx)", "נוסחאות מובנות"],
    image: "xlsx-budget.webp",
    downloadUrl: "downloads/monthly-budget.xlsx",
    featured: true,
    heroDesc: "גיליון Excel לניהול תקציב חודשי אישי — רושמים הכנסות והוצאות מול קטגוריות, והסיכום (סה\"כ הכנסות, סה\"כ הוצאות, יתרה) מתעדכן אוטומטית באמצעות נוסחאות. התאים הצהובים הם היחידים שצריך למלא.",
    checklist: [
      "נוסחאות אמיתיות — לא מספרים קבועים שצריך לעדכן ידנית",
      "תאים צהובים מסמנים בדיוק מה למלא",
      "סיכום הכנסות/הוצאות/יתרה מתעדכן לבד",
      "הורדה מיידית וחינמית, קובץ Excel רגיל",
    ],
  },
  {
    slug: "xlsx-invoice",
    category: "גיליונות",
    categorySlug: "xlsx",
    topicSlug: "finance",
    title: "תבנית חשבונית עסקית",
    shortDesc: "גיליון Excel לחשבונית עם חישוב מע\"מ אוטומטי. חינם.",
    price: 0,
    format: "Excel (.xlsx)",
    formatBadges: ["חינם", "קובץ Excel (.xlsx)", "נוסחאות מובנות"],
    image: "xlsx-invoice.webp",
    downloadUrl: "downloads/invoice-template.xlsx",
    heroDesc: "גיליון Excel לחשבונית עסקית — פרטי העסק והלקוח, טבלת שורות עם כמות ומחיר יחידה, וסיכום עם סכום ביניים, מע\"מ (17%) וסה\"כ לתשלום, הכול מחושב אוטומטית בנוסחאות.",
    checklist: [
      "חישוב אוטומטי של סה\"כ לכל שורה (כמות × מחיר)",
      "מע\"מ וסה\"כ לתשלום מחושבים לבד",
      "תאים צהובים מסמנים בדיוק מה למלא",
      "הורדה מיידית וחינמית, קובץ Excel רגיל",
    ],
  },
  {
    slug: "xlsx-expense",
    category: "גיליונות",
    categorySlug: "xlsx",
    topicSlug: "finance",
    title: "תבנית מעקב הוצאות עסק",
    shortDesc: "גיליון Excel למעקב הוצאות עסקיות לפי קטגוריה וספק, עם סיכומים אוטומטיים. חינם.",
    price: 0,
    format: "Excel (.xlsx)",
    formatBadges: ["חינם", "קובץ Excel (.xlsx)", "נוסחאות מובנות"],
    image: "xlsx-expense.webp",
    downloadUrl: "downloads/expense-tracker.xlsx",
    heroDesc: "גיליון Excel למעקב הוצאות שוטפות של העסק — תאריך, קטגוריה, ספק, תיאור וסכום לכל הוצאה. הסיכום למטה מחשב לבד סה\"כ לכל קטגוריה (שכירות, ציוד, שיווק, תוכנה, הובלות ועוד) וסה\"כ הוצאות כללי, כדי לדעת בכל רגע לאן הכסף הולך.",
    checklist: [
      "פילוח אוטומטי של ההוצאות לפי קטגוריה",
      "תאים צהובים מסמנים בדיוק מה למלא",
      "כמה שורות ריקות מוכנות מראש להמשך מילוי",
      "הורדה מיידית וחינמית, קובץ Excel רגיל",
    ],
  },
  {
    slug: "xlsx-clients",
    category: "גיליונות",
    categorySlug: "xlsx",
    topicSlug: "customers",
    title: "תבנית מעקב לקוחות",
    shortDesc: "גיליון Excel פשוט למעקב לידים ולקוחות — פרטי קשר, סטטוס והערות. חינם.",
    price: 0,
    format: "Excel (.xlsx)",
    formatBadges: ["חינם", "קובץ Excel (.xlsx)", "נוסחאות מובנות"],
    image: "xlsx-clients.webp",
    downloadUrl: "downloads/client-tracker.xlsx",
    heroDesc: "גיליון Excel לניהול לקוחות ולידים בלי צורך במערכת CRM מסובכת — שם, טלפון, אימייל, סטטוס (ליד / פעיל / סגור), תאריך פנייה ראשונה והערות חופשיות. הסיכום למטה סופר לבד כמה לקוחות בכל סטטוס וסה\"כ לקוחות.",
    checklist: [
      "ספירה אוטומטית של לקוחות לפי סטטוס",
      "תאים צהובים מסמנים בדיוק מה למלא",
      "כמה שורות ריקות מוכנות מראש להמשך מילוי",
      "הורדה מיידית וחינמית, קובץ Excel רגיל",
    ],
  },
  {
    slug: "xlsx-cashflow",
    category: "גיליונות",
    categorySlug: "xlsx",
    topicSlug: "finance",
    title: "תבנית תזרים מזומנים",
    shortDesc: "גיליון Excel לתזרים מזומנים חודשי, עם יתרות שמתגלגלות אוטומטית מחודש לחודש. חינם.",
    price: 0,
    format: "Excel (.xlsx)",
    formatBadges: ["חינם", "קובץ Excel (.xlsx)", "נוסחאות מובנות"],
    image: "xlsx-cashflow.webp",
    downloadUrl: "downloads/cash-flow-forecast.xlsx",
    heroDesc: "גיליון Excel לתחזית תזרים מזומנים — לכל חודש הכנסות והוצאות, ויתרת הסגירה שלו הופכת אוטומטית ליתרת הפתיחה של החודש הבא. כך רואים מראש אם יהיה מספיק מזומן בקופה, ולא רק בדיעבד.",
    checklist: [
      "יתרות מתגלגלות אוטומטית מחודש לחודש",
      "תאים צהובים מסמנים בדיוק מה למלא",
      "סיכום תקופתי של הכנסות, הוצאות ויתרת סגירה",
      "הורדה מיידית וחינמית, קובץ Excel רגיל",
    ],
  },
  {
    slug: "xlsx-inventory",
    category: "גיליונות",
    categorySlug: "xlsx",
    topicSlug: "operations",
    title: "תבנית מעקב מלאי",
    shortDesc: "גיליון Excel למעקב מלאי עם שווי מלאי וסטטוס \"להזמין מחדש\" שמחושבים לבד. חינם.",
    price: 0,
    format: "Excel (.xlsx)",
    formatBadges: ["חינם", "קובץ Excel (.xlsx)", "נוסחאות מובנות"],
    image: "xlsx-inventory.webp",
    downloadUrl: "downloads/inventory-tracker.xlsx",
    heroDesc: "גיליון Excel לניהול מלאי — לכל פריט כמות במלאי, נקודת הזמנה מחדש ועלות ליחידה. שווי המלאי מחושב אוטומטית, וכל פריט שירד מתחת לנקודת ההזמנה מחדש מסומן לבד כ\"להזמין מחדש\" — בלי צורך לעבור ידנית על כל השורות.",
    checklist: [
      "שווי מלאי מחושב אוטומטית לכל פריט ובסה\"כ",
      "סימון \"להזמין מחדש\" אוטומטי לפי נקודת ההזמנה שהגדרתם",
      "תאים צהובים מסמנים בדיוק מה למלא",
      "הורדה מיידית וחינמית, קובץ Excel רגיל",
    ],
  },
  {
    slug: "xlsx-timeline",
    category: "גיליונות",
    categorySlug: "xlsx",
    topicSlug: "projects",
    title: "תבנית לוח זמנים לפרויקט",
    shortDesc: "גיליון Excel לניהול משימות בפרויקט, עם משך וסטטוס (בתהליך/באיחור/הושלם) שמחושבים לבד. חינם.",
    price: 0,
    format: "Excel (.xlsx)",
    formatBadges: ["חינם", "קובץ Excel (.xlsx)", "נוסחאות מובנות"],
    image: "xlsx-timeline.webp",
    downloadUrl: "downloads/project-timeline.xlsx",
    heroDesc: "גיליון Excel לניהול לוח זמנים של פרויקט — לכל משימה אחראי, תאריכי התחלה וסיום ואחוז השלמה. משך המשימה מחושב אוטומטית, והסטטוס (\"בתהליך\" / \"באיחור\" / \"הושלם\") מתעדכן לבד מול התאריך של היום.",
    checklist: [
      "משך כל משימה מחושב אוטומטית מהתאריכים",
      "סטטוס \"באיחור\" מסומן לבד מול תאריך היום",
      "תאים צהובים מסמנים בדיוק מה למלא",
      "הורדה מיידית וחינמית, קובץ Excel רגיל",
    ],
  },
  {
    slug: "xlsx-pnl",
    category: "גיליונות",
    categorySlug: "xlsx",
    topicSlug: "finance",
    title: "תבנית דוח רווח והפסד",
    shortDesc: "גיליון Excel לדוח רווח והפסד חודשי, עם רווח גולמי, רווח נקי ואחוזי רווחיות שמחושבים לבד. חינם.",
    price: 0,
    format: "Excel (.xlsx)",
    formatBadges: ["חינם", "קובץ Excel (.xlsx)", "נוסחאות מובנות"],
    image: "xlsx-pnl.webp",
    downloadUrl: "downloads/profit-loss-statement.xlsx",
    heroDesc: "גיליון Excel לדוח רווח והפסד חודשי — הכנסות, עלות המכר והוצאות תפעוליות מסודרות לפי סעיפים. הרווח הגולמי, הרווח הנקי ואחוזי הרווחיות מחושבים אוטומטית, כדי לראות בבירור כמה נשאר בסוף מכל שקל שנכנס.",
    checklist: [
      "רווח גולמי ורווח נקי מחושבים אוטומטית",
      "אחוזי רווחיות מוצגים לצד הסכומים",
      "תאים צהובים מסמנים בדיוק מה למלא",
      "הורדה מיידית וחינמית, קובץ Excel רגיל",
    ],
  },
  {
    slug: "xlsx-timesheet",
    category: "גיליונות",
    categorySlug: "xlsx",
    topicSlug: "hr",
    title: "תבנית מעקב שעות עבודה",
    shortDesc: "גיליון Excel למעקב שעות עובדים, עם שעות עבודה ושכר לתשלום שמחושבים לבד לפי תעריף. חינם.",
    price: 0,
    format: "Excel (.xlsx)",
    formatBadges: ["חינם", "קובץ Excel (.xlsx)", "נוסחאות מובנות"],
    image: "xlsx-timesheet.webp",
    downloadUrl: "downloads/timesheet-tracker.xlsx",
    heroDesc: "גיליון Excel למעקב שעות עבודה — תאריך, עובד, שעת התחלה ושעת סיום לכל משמרת. מספר שעות העבודה וסך התשלום (לפי תעריף לשעה) מחושבים אוטומטית, כולל סיכום כולל בתחתית.",
    checklist: [
      "שעות עבודה מחושבות אוטומטית משעת התחלה וסיום",
      "סה\"כ לתשלום מחושב אוטומטית לפי תעריף",
      "תאים צהובים מסמנים בדיוק מה למלא",
      "הורדה מיידית וחינמית, קובץ Excel רגיל",
    ],
  },
  {
    slug: "xlsx-breakeven",
    category: "גיליונות",
    categorySlug: "xlsx",
    topicSlug: "finance",
    title: "תבנית נקודת איזון ותמחור",
    shortDesc: "גיליון Excel לחישוב נקודת איזון ותמחור — כמה יחידות צריך למכור כדי לכסות הוצאות. חינם.",
    price: 0,
    format: "Excel (.xlsx)",
    formatBadges: ["חינם", "קובץ Excel (.xlsx)", "נוסחאות מובנות"],
    image: "xlsx-breakeven.webp",
    downloadUrl: "downloads/breakeven-pricing.xlsx",
    heroDesc: "גיליון Excel לחישוב נקודת איזון ותמחור — מזינים הוצאות קבועות, עלות משתנה ליחידה ומחיר מכירה, והגיליון מחשב לבד כמה יחידות צריך למכור כדי לכסות את ההוצאות, וטבלת תרחישים שמראה רווח/הפסד בכמה רמות מכירה.",
    checklist: [
      "נקודת איזון (ביחידות ובש\"ח) מחושבת אוטומטית",
      "טבלת תרחישי רווח/הפסד לפי כמות יחידות שנמכרו",
      "תאים צהובים מסמנים בדיוק מה למלא",
      "הורדה מיידית וחינמית, קובץ Excel רגיל",
    ],
  },
  {
    slug: "xlsx-salestargets",
    category: "גיליונות",
    categorySlug: "xlsx",
    topicSlug: "sales",
    title: "תבנית מכירות מול יעדים",
    shortDesc: "גיליון Excel למעקב מכירות מול יעד חודשי, עם אחוז השגה ומצטבר שמחושבים לבד. חינם.",
    price: 0,
    format: "Excel (.xlsx)",
    formatBadges: ["חינם", "קובץ Excel (.xlsx)", "נוסחאות מובנות"],
    image: "xlsx-salestargets.webp",
    downloadUrl: "downloads/sales-targets-tracker.xlsx",
    heroDesc: "גיליון Excel למעקב מכירות מול יעדים — לכל חודש יעד מכירות מול מכירות בפועל. אחוז ההשגה, הפער מהיעד והמכירות המצטברות מחושבים אוטומטית, כדי לראות בכל רגע איפה עומדים ביחס ליעד השנתי.",
    checklist: [
      "אחוז השגת יעד מחושב אוטומטית לכל חודש",
      "מכירות מצטברות לאורך התקופה מתעדכנות לבד",
      "תאים צהובים מסמנים בדיוק מה למלא",
      "הורדה מיידית וחינמית, קובץ Excel רגיל",
    ],
  },
  {
    slug: "xlsx-vendors",
    category: "גיליונות",
    categorySlug: "xlsx",
    topicSlug: "operations",
    title: "תבנית השוואת ספקים",
    shortDesc: "גיליון Excel להשוואת ספקים לפי מחיר, זמן אספקה ואיכות, עם המלצה אוטומטית לספק המתאים. חינם.",
    price: 0,
    format: "Excel (.xlsx)",
    formatBadges: ["חינם", "קובץ Excel (.xlsx)", "נוסחאות מובנות"],
    image: "xlsx-vendors.webp",
    downloadUrl: "downloads/vendor-comparison.xlsx",
    heroDesc: "גיליון Excel להשוואת ספקים — לכל ספק מחיר, זמן אספקה ודירוג איכות. הגיליון מחשב ציון משוקלל לכל ספק וממליץ אוטומטית על הספק עם הציון הגבוה ביותר, כדי לקבל החלטה מבוססת ולא רק לפי המחיר הזול ביותר.",
    checklist: [
      "ציון משוקלל מחושב אוטומטית לכל ספק",
      "הספק המומלץ מסומן אוטומטית לפי הציון הגבוה ביותר",
      "תאים צהובים מסמנים בדיוק מה למלא",
      "הורדה מיידית וחינמית, קובץ Excel רגיל",
    ],
  },
];

/* Two real axes, not one flat list: WHAT KIND of document (top-level
   type — every product belongs to exactly one), and for CVs specifically,
   WHICH PROFESSION they're written for (a second, narrower filter that
   only makes sense once "קורות חיים" is already selected — a deck or a
   spreadsheet was never "for developers" the way a CV is). Mixing both
   axes into one row of pills (the old CATEGORIES array) is exactly what
   read as cluttered: "כללי" and "מצגות" look like peers but aren't. */
const PRODUCT_TYPES = [
  { slug: "cv", label: "קורות חיים", labelEn: "Resumes" },
  { slug: "deck", label: "מצגות עסקיות", labelEn: "Business decks" },
  { slug: "xlsx", label: "גיליונות Excel", labelEn: "Excel spreadsheets" },
];
/* products.html is one page reused per ?type= — each type gets its own
   dedicated-feeling hero (title + lead), the same way sites.html has its
   own, instead of one generic "קטלוג המוצרים" header regardless of which
   type is actually showing. */
const TYPE_HERO = {
  cv: { title: "קורות חיים", lead: "תבניות קורות חיים מוכנות, בעיצוב מקצועי — ממלאים פרטים ורואים תוצאה חיה, לפי מקצוע.",
        titleEn: "Resumes", leadEn: "Ready-made, professionally designed resume templates — fill in your details and see a live result, by profession." },
  deck: { title: "מצגות עסקיות", lead: "תבניות PowerPoint מוכנות להורדה ועריכה — לכל צורך: פרופיל חברה, השקת מוצר, גיוס משקיעים ועוד.",
          titleEn: "Business decks", leadEn: "Ready-to-download, ready-to-edit PowerPoint templates — for any need: company profile, product launch, fundraising and more." },
  xlsx: { title: "גיליונות Excel", lead: "כלי ניהול מוכנים להורדה — תקציב, חשבוניות, מעקב הוצאות ולקוחות.",
          titleEn: "Excel spreadsheets", leadEn: "Ready-to-download management tools — budgeting, invoicing, expense and customer tracking." },
};
const CV_PROFESSIONS = [
  { slug: "all", label: "הכל", labelEn: "All" },
  { slug: "general", label: "כללי", labelEn: "General" },
  { slug: "dev", label: "תכנות", labelEn: "Development" },
  { slug: "design", label: "עיצוב", labelEn: "Design" },
  { slug: "accounting", label: "הנהלת חשבונות", labelEn: "Accounting" },
];
const DECK_TOPICS = [
  { slug: "all", label: "הכל", labelEn: "All" },
  { slug: "business", label: "עסקי", labelEn: "Business" },
  { slug: "marketing", label: "שיווק ותוכן", labelEn: "Marketing & content" },
  { slug: "creative", label: "יצירתי", labelEn: "Creative" },
];
const XLSX_TOPICS = [
  { slug: "all", label: "הכל", labelEn: "All" },
  { slug: "finance", label: "ניהול כספים", labelEn: "Finance" },
  { slug: "customers", label: "ניהול לקוחות", labelEn: "Customer management" },
  { slug: "operations", label: "תפעול ומלאי", labelEn: "Operations & inventory" },
  { slug: "projects", label: "ניהול פרויקטים", labelEn: "Project management" },
  { slug: "sales", label: "מכירות", labelEn: "Sales" },
  { slug: "hr", label: "כוח אדם ושעות עבודה", labelEn: "HR & timesheets" },
];
/* One lookup per type instead of a parallel if/else chain everywhere a
   type's sub-topic list is needed (catalog.js's initProductsPage). */
const TYPE_SUBTOPICS = { cv: CV_PROFESSIONS, deck: DECK_TOPICS, xlsx: XLSX_TOPICS };

function productType(p) {
  if (p.categorySlug === "deck") return "deck";
  if (p.categorySlug === "xlsx") return "xlsx";
  return "cv";
}
/* CV items already carry their sub-topic (profession) in categorySlug —
   decks/spreadsheets use a separate topicSlug field instead, since their
   categorySlug already means "deck"/"xlsx" (the type itself). */
function productSubtopic(p) {
  if (p.categorySlug === "deck" || p.categorySlug === "xlsx") return p.topicSlug || "";
  return p.categorySlug;
}
/* The catalog card's colored tag showed the flat type label ("מצגות" /
   "גיליונות") for every deck/xlsx product regardless of topic, so the
   new per-topic card color (see .card[data-cat=…] in style.css) had
   nothing matching in the visible text. Falls back to p.category (CV
   items, or a deck/xlsx item somehow missing a topicSlug) unchanged. */
function productSubtopicLabel(p) {
  const topic = productSubtopic(p);
  const list = TYPE_SUBTOPICS[productType(p)] || [];
  const match = list.find((t) => t.slug === topic);
  const isEn = typeof currentLang === "function" && currentLang() === "en";
  if (match) return (isEn && match.labelEn) || match.label;
  return p.category;
}
